/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./components/**/*.{vue,js,ts}",
    "./layouts/**/*.{vue,js,ts}",
    "./pages/**/*.{vue,js,ts}",
    "./app.vue",
    "./error.vue",
    "./nuxt.config.ts",
  ],
  theme: {
    extend: {
      // Add any custom extensions here if needed
    },
  },
  plugins: [],
  safelist: [
    // Shadow sizes - base shadows
    "shadow-2xs",
    "shadow-xs",
    "shadow-sm",
    "shadow-md",
    "shadow-lg",
    "shadow-xl",
    "shadow-2xl",
    "shadow-none",

    // Special shadow colors
    "shadow-inherit",
    "shadow-current",
    "shadow-transparent",
    "shadow-black",
    "shadow-white",
    "shadow-white/10",
    "shadow-white/20",
    "shadow-white/25",
    "shadow-white/30",
    "shadow-white/40",
    "shadow-white/50",
    "shadow-black/10",
    "shadow-black/20",
    "shadow-black/25",
    "shadow-black/30",
    "shadow-black/40",
    "shadow-black/50",

    // Red shadows - all shades
    "shadow-red-50",
    "shadow-red-100",
    "shadow-red-200",
    "shadow-red-300",
    "shadow-red-400",
    "shadow-red-500",
    "shadow-red-600",
    "shadow-red-700",
    "shadow-red-800",
    "shadow-red-900",
    "shadow-red-950",

    // Orange shadows - all shades
    "shadow-orange-50",
    "shadow-orange-100",
    "shadow-orange-200",
    "shadow-orange-300",
    "shadow-orange-400",
    "shadow-orange-500",
    "shadow-orange-600",
    "shadow-orange-700",
    "shadow-orange-800",
    "shadow-orange-900",
    "shadow-orange-950",

    // Amber shadows - all shades
    "shadow-amber-50",
    "shadow-amber-100",
    "shadow-amber-200",
    "shadow-amber-300",
    "shadow-amber-400",
    "shadow-amber-500",
    "shadow-amber-600",
    "shadow-amber-700",
    "shadow-amber-800",
    "shadow-amber-900",
    "shadow-amber-950",

    // Yellow shadows - all shades
    "shadow-yellow-50",
    "shadow-yellow-100",
    "shadow-yellow-200",
    "shadow-yellow-300",
    "shadow-yellow-400",
    "shadow-yellow-500",
    "shadow-yellow-600",
    "shadow-yellow-700",
    "shadow-yellow-800",
    "shadow-yellow-900",
    "shadow-yellow-950",

    // Lime shadows - all shades
    "shadow-lime-50",
    "shadow-lime-100",
    "shadow-lime-200",
    "shadow-lime-300",
    "shadow-lime-400",
    "shadow-lime-500",
    "shadow-lime-600",
    "shadow-lime-700",
    "shadow-lime-800",
    "shadow-lime-900",
    "shadow-lime-950",

    // Green shadows - all shades
    "shadow-green-50",
    "shadow-green-100",
    "shadow-green-200",
    "shadow-green-300",
    "shadow-green-400",
    "shadow-green-500",
    "shadow-green-600",
    "shadow-green-700",
    "shadow-green-800",
    "shadow-green-900",
    "shadow-green-950",

    // Emerald shadows - all shades
    "shadow-emerald-50",
    "shadow-emerald-100",
    "shadow-emerald-200",
    "shadow-emerald-300",
    "shadow-emerald-400",
    "shadow-emerald-500",
    "shadow-emerald-600",
    "shadow-emerald-700",
    "shadow-emerald-800",
    "shadow-emerald-900",
    "shadow-emerald-950",

    // Teal shadows - all shades
    "shadow-teal-50",
    "shadow-teal-100",
    "shadow-teal-200",
    "shadow-teal-300",
    "shadow-teal-400",
    "shadow-teal-500",
    "shadow-teal-600",
    "shadow-teal-700",
    "shadow-teal-800",
    "shadow-teal-900",
    "shadow-teal-950",

    // Cyan shadows - all shades
    "shadow-cyan-50",
    "shadow-cyan-100",
    "shadow-cyan-200",
    "shadow-cyan-300",
    "shadow-cyan-400",
    "shadow-cyan-500",
    "shadow-cyan-600",
    "shadow-cyan-700",
    "shadow-cyan-800",
    "shadow-cyan-900",
    "shadow-cyan-950",

    // Sky shadows - all shades
    "shadow-sky-50",
    "shadow-sky-100",
    "shadow-sky-200",
    "shadow-sky-300",
    "shadow-sky-400",
    "shadow-sky-500",
    "shadow-sky-600",
    "shadow-sky-700",
    "shadow-sky-800",
    "shadow-sky-900",
    "shadow-sky-950",

    // Blue shadows - all shades
    "shadow-blue-50",
    "shadow-blue-100",
    "shadow-blue-200",
    "shadow-blue-300",
    "shadow-blue-400",
    "shadow-blue-500",
    "shadow-blue-600",
    "shadow-blue-700",
    "shadow-blue-800",
    "shadow-blue-900",
    "shadow-blue-950",

    // Indigo shadows - all shades
    "shadow-indigo-50",
    "shadow-indigo-100",
    "shadow-indigo-200",
    "shadow-indigo-300",
    "shadow-indigo-400",
    "shadow-indigo-500",
    "shadow-indigo-600",
    "shadow-indigo-700",
    "shadow-indigo-800",
    "shadow-indigo-900",
    "shadow-indigo-950",

    // Violet shadows - all shades
    "shadow-violet-50",
    "shadow-violet-100",
    "shadow-violet-200",
    "shadow-violet-300",
    "shadow-violet-400",
    "shadow-violet-500",
    "shadow-violet-600",
    "shadow-violet-700",
    "shadow-violet-800",
    "shadow-violet-900",
    "shadow-violet-950",

    // Purple shadows - all shades
    "shadow-purple-50",
    "shadow-purple-100",
    "shadow-purple-200",
    "shadow-purple-300",
    "shadow-purple-400",
    "shadow-purple-500",
    "shadow-purple-600",
    "shadow-purple-700",
    "shadow-purple-800",
    "shadow-purple-900",
    "shadow-purple-950",

    // Fuchsia shadows - all shades
    "shadow-fuchsia-50",
    "shadow-fuchsia-100",
    "shadow-fuchsia-200",
    "shadow-fuchsia-300",
    "shadow-fuchsia-400",
    "shadow-fuchsia-500",
    "shadow-fuchsia-600",
    "shadow-fuchsia-700",
    "shadow-fuchsia-800",
    "shadow-fuchsia-900",
    "shadow-fuchsia-950",

    // Pink shadows - all shades
    "shadow-pink-50",
    "shadow-pink-100",
    "shadow-pink-200",
    "shadow-pink-300",
    "shadow-pink-400",
    "shadow-pink-500",
    "shadow-pink-600",
    "shadow-pink-700",
    "shadow-pink-800",
    "shadow-pink-900",
    "shadow-pink-950",

    // Rose shadows - all shades
    "shadow-rose-50",
    "shadow-rose-100",
    "shadow-rose-200",
    "shadow-rose-300",
    "shadow-rose-400",
    "shadow-rose-500",
    "shadow-rose-600",
    "shadow-rose-700",
    "shadow-rose-800",
    "shadow-rose-900",
    "shadow-rose-950",

    // Gray shadows - all shades
    "shadow-gray-50",
    "shadow-gray-100",
    "shadow-gray-200",
    "shadow-gray-300",
    "shadow-gray-400",
    "shadow-gray-500",
    "shadow-gray-600",
    "shadow-gray-700",
    "shadow-gray-800",
    "shadow-gray-900",
    "shadow-gray-950",

    // Slate shadows - all shades
    "shadow-slate-50",
    "shadow-slate-100",
    "shadow-slate-200",
    "shadow-slate-300",
    "shadow-slate-400",
    "shadow-slate-500",
    "shadow-slate-600",
    "shadow-slate-700",
    "shadow-slate-800",
    "shadow-slate-900",
    "shadow-slate-950",

    // Zinc shadows - all shades
    "shadow-zinc-50",
    "shadow-zinc-100",
    "shadow-zinc-200",
    "shadow-zinc-300",
    "shadow-zinc-400",
    "shadow-zinc-500",
    "shadow-zinc-600",
    "shadow-zinc-700",
    "shadow-zinc-800",
    "shadow-zinc-900",
    "shadow-zinc-950",

    // Neutral shadows - all shades
    "shadow-neutral-50",
    "shadow-neutral-100",
    "shadow-neutral-200",
    "shadow-neutral-300",
    "shadow-neutral-400",
    "shadow-neutral-500",
    "shadow-neutral-600",
    "shadow-neutral-700",
    "shadow-neutral-800",
    "shadow-neutral-900",
    "shadow-neutral-950",

    // Stone shadows - all shades
    "shadow-stone-50",
    "shadow-stone-100",
    "shadow-stone-200",
    "shadow-stone-300",
    "shadow-stone-400",
    "shadow-stone-500",
    "shadow-stone-600",
    "shadow-stone-700",
    "shadow-stone-800",
    "shadow-stone-900",
    "shadow-stone-950",

    // Dark mode variants - Special colors
    "dark:shadow-inherit",
    "dark:shadow-current",
    "dark:shadow-transparent",
    "dark:shadow-black",
    "dark:shadow-white",
    "dark:shadow-white/10",
    "dark:shadow-white/20",
    "dark:shadow-white/25",
    "dark:shadow-white/30",
    "dark:shadow-white/40",
    "dark:shadow-white/50",
    "dark:shadow-black/10",
    "dark:shadow-black/20",
    "dark:shadow-black/25",
    "dark:shadow-black/30",
    "dark:shadow-black/40",
    "dark:shadow-black/50",

    // Dark mode Red shadows
    "dark:shadow-red-50",
    "dark:shadow-red-100",
    "dark:shadow-red-200",
    "dark:shadow-red-300",
    "dark:shadow-red-400",
    "dark:shadow-red-500",
    "dark:shadow-red-600",
    "dark:shadow-red-700",
    "dark:shadow-red-800",
    "dark:shadow-red-900",
    "dark:shadow-red-950",

    // Dark mode Orange shadows
    "dark:shadow-orange-50",
    "dark:shadow-orange-100",
    "dark:shadow-orange-200",
    "dark:shadow-orange-300",
    "dark:shadow-orange-400",
    "dark:shadow-orange-500",
    "dark:shadow-orange-600",
    "dark:shadow-orange-700",
    "dark:shadow-orange-800",
    "dark:shadow-orange-900",
    "dark:shadow-orange-950",

    // Dark mode Amber shadows
    "dark:shadow-amber-50",
    "dark:shadow-amber-100",
    "dark:shadow-amber-200",
    "dark:shadow-amber-300",
    "dark:shadow-amber-400",
    "dark:shadow-amber-500",
    "dark:shadow-amber-600",
    "dark:shadow-amber-700",
    "dark:shadow-amber-800",
    "dark:shadow-amber-900",
    "dark:shadow-amber-950",

    // Dark mode Yellow shadows
    "dark:shadow-yellow-50",
    "dark:shadow-yellow-100",
    "dark:shadow-yellow-200",
    "dark:shadow-yellow-300",
    "dark:shadow-yellow-400",
    "dark:shadow-yellow-500",
    "dark:shadow-yellow-600",
    "dark:shadow-yellow-700",
    "dark:shadow-yellow-800",
    "dark:shadow-yellow-900",
    "dark:shadow-yellow-950",

    // Dark mode Lime shadows
    "dark:shadow-lime-50",
    "dark:shadow-lime-100",
    "dark:shadow-lime-200",
    "dark:shadow-lime-300",
    "dark:shadow-lime-400",
    "dark:shadow-lime-500",
    "dark:shadow-lime-600",
    "dark:shadow-lime-700",
    "dark:shadow-lime-800",
    "dark:shadow-lime-900",
    "dark:shadow-lime-950",

    // Dark mode Green shadows
    "dark:shadow-green-50",
    "dark:shadow-green-100",
    "dark:shadow-green-200",
    "dark:shadow-green-300",
    "dark:shadow-green-400",
    "dark:shadow-green-500",
    "dark:shadow-green-600",
    "dark:shadow-green-700",
    "dark:shadow-green-800",
    "dark:shadow-green-900",
    "dark:shadow-green-950",

    // Dark mode Emerald shadows
    "dark:shadow-emerald-50",
    "dark:shadow-emerald-100",
    "dark:shadow-emerald-200",
    "dark:shadow-emerald-300",
    "dark:shadow-emerald-400",
    "dark:shadow-emerald-500",
    "dark:shadow-emerald-600",
    "dark:shadow-emerald-700",
    "dark:shadow-emerald-800",
    "dark:shadow-emerald-900",
    "dark:shadow-emerald-950",

    // Dark mode Teal shadows
    "dark:shadow-teal-50",
    "dark:shadow-teal-100",
    "dark:shadow-teal-200",
    "dark:shadow-teal-300",
    "dark:shadow-teal-400",
    "dark:shadow-teal-500",
    "dark:shadow-teal-600",
    "dark:shadow-teal-700",
    "dark:shadow-teal-800",
    "dark:shadow-teal-900",
    "dark:shadow-teal-950",

    // Dark mode Cyan shadows
    "dark:shadow-cyan-50",
    "dark:shadow-cyan-100",
    "dark:shadow-cyan-200",
    "dark:shadow-cyan-300",
    "dark:shadow-cyan-400",
    "dark:shadow-cyan-500",
    "dark:shadow-cyan-600",
    "dark:shadow-cyan-700",
    "dark:shadow-cyan-800",
    "dark:shadow-cyan-900",
    "dark:shadow-cyan-950",

    // Dark mode Sky shadows
    "dark:shadow-sky-50",
    "dark:shadow-sky-100",
    "dark:shadow-sky-200",
    "dark:shadow-sky-300",
    "dark:shadow-sky-400",
    "dark:shadow-sky-500",
    "dark:shadow-sky-600",
    "dark:shadow-sky-700",
    "dark:shadow-sky-800",
    "dark:shadow-sky-900",
    "dark:shadow-sky-950",

    // Dark mode Blue shadows
    "dark:shadow-blue-50",
    "dark:shadow-blue-100",
    "dark:shadow-blue-200",
    "dark:shadow-blue-300",
    "dark:shadow-blue-400",
    "dark:shadow-blue-500",
    "dark:shadow-blue-600",
    "dark:shadow-blue-700",
    "dark:shadow-blue-800",
    "dark:shadow-blue-900",
    "dark:shadow-blue-950",

    // Dark mode Indigo shadows
    "dark:shadow-indigo-50",
    "dark:shadow-indigo-100",
    "dark:shadow-indigo-200",
    "dark:shadow-indigo-300",
    "dark:shadow-indigo-400",
    "dark:shadow-indigo-500",
    "dark:shadow-indigo-600",
    "dark:shadow-indigo-700",
    "dark:shadow-indigo-800",
    "dark:shadow-indigo-900",
    "dark:shadow-indigo-950",

    // Dark mode Violet shadows
    "dark:shadow-violet-50",
    "dark:shadow-violet-100",
    "dark:shadow-violet-200",
    "dark:shadow-violet-300",
    "dark:shadow-violet-400",
    "dark:shadow-violet-500",
    "dark:shadow-violet-600",
    "dark:shadow-violet-700",
    "dark:shadow-violet-800",
    "dark:shadow-violet-900",
    "dark:shadow-violet-950",

    // Dark mode Purple shadows
    "dark:shadow-purple-50",
    "dark:shadow-purple-100",
    "dark:shadow-purple-200",
    "dark:shadow-purple-300",
    "dark:shadow-purple-400",
    "dark:shadow-purple-500",
    "dark:shadow-purple-600",
    "dark:shadow-purple-700",
    "dark:shadow-purple-800",
    "dark:shadow-purple-900",
    "dark:shadow-purple-950",

    // Dark mode Fuchsia shadows
    "dark:shadow-fuchsia-50",
    "dark:shadow-fuchsia-100",
    "dark:shadow-fuchsia-200",
    "dark:shadow-fuchsia-300",
    "dark:shadow-fuchsia-400",
    "dark:shadow-fuchsia-500",
    "dark:shadow-fuchsia-600",
    "dark:shadow-fuchsia-700",
    "dark:shadow-fuchsia-800",
    "dark:shadow-fuchsia-900",
    "dark:shadow-fuchsia-950",

    // Dark mode Pink shadows
    "dark:shadow-pink-50",
    "dark:shadow-pink-100",
    "dark:shadow-pink-200",
    "dark:shadow-pink-300",
    "dark:shadow-pink-400",
    "dark:shadow-pink-500",
    "dark:shadow-pink-600",
    "dark:shadow-pink-700",
    "dark:shadow-pink-800",
    "dark:shadow-pink-900",
    "dark:shadow-pink-950",

    // Dark mode Rose shadows
    "dark:shadow-rose-50",
    "dark:shadow-rose-100",
    "dark:shadow-rose-200",
    "dark:shadow-rose-300",
    "dark:shadow-rose-400",
    "dark:shadow-rose-500",
    "dark:shadow-rose-600",
    "dark:shadow-rose-700",
    "dark:shadow-rose-800",
    "dark:shadow-rose-900",
    "dark:shadow-rose-950",

    // Dark mode Gray shadows
    "dark:shadow-gray-50",
    "dark:shadow-gray-100",
    "dark:shadow-gray-200",
    "dark:shadow-gray-300",
    "dark:shadow-gray-400",
    "dark:shadow-gray-500",
    "dark:shadow-gray-600",
    "dark:shadow-gray-700",
    "dark:shadow-gray-800",
    "dark:shadow-gray-900",
    "dark:shadow-gray-950",

    // Dark mode Slate shadows
    "dark:shadow-slate-50",
    "dark:shadow-slate-100",
    "dark:shadow-slate-200",
    "dark:shadow-slate-300",
    "dark:shadow-slate-400",
    "dark:shadow-slate-500",
    "dark:shadow-slate-600",
    "dark:shadow-slate-700",
    "dark:shadow-slate-800",
    "dark:shadow-slate-900",
    "dark:shadow-slate-950",

    // Dark mode Zinc shadows
    "dark:shadow-zinc-50",
    "dark:shadow-zinc-100",
    "dark:shadow-zinc-200",
    "dark:shadow-zinc-300",
    "dark:shadow-zinc-400",
    "dark:shadow-zinc-500",
    "dark:shadow-zinc-600",
    "dark:shadow-zinc-700",
    "dark:shadow-zinc-800",
    "dark:shadow-zinc-900",
    "dark:shadow-zinc-950",

    // Dark mode Neutral shadows
    "dark:shadow-neutral-50",
    "dark:shadow-neutral-100",
    "dark:shadow-neutral-200",
    "dark:shadow-neutral-300",
    "dark:shadow-neutral-400",
    "dark:shadow-neutral-500",
    "dark:shadow-neutral-600",
    "dark:shadow-neutral-700",
    "dark:shadow-neutral-800",
    "dark:shadow-neutral-900",
    "dark:shadow-neutral-950",

    // Dark mode Stone shadows
    "dark:shadow-stone-50",
    "dark:shadow-stone-100",
    "dark:shadow-stone-200",
    "dark:shadow-stone-300",
    "dark:shadow-stone-400",
    "dark:shadow-stone-500",
    "dark:shadow-stone-600",
    "dark:shadow-stone-700",
    "dark:shadow-stone-800",
    "dark:shadow-stone-900",
    "dark:shadow-stone-950",
  ],
};
